name: Build Typst PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: typst/typst-action@v1
        with:
          source: main.typ

      - uses: actions/upload-artifact@v3
        with:
          name: thesis-pdf
          path: main.pdf